version: "3.9"

services:
  api:
    build: .
    container_name: tb-api-skd
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - tb-net

networks:
  tb-net:
    driver: bridge 